/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'selector-class-pattern': null,
    'custom-property-pattern': null,
    'keyframes-name-pattern': null,
    'no-descending-specificity': null,
    'color-hex-length': null,
    'color-function-notation': null,
    'alpha-value-notation': null,
    'color-function-alias-notation': null,
    'value-keyword-case': null,
    'shorthand-property-no-redundant-values': null,
    'number-max-precision': null,
    'declaration-block-single-line-max-declarations': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'font-family-no-missing-generic-family-keyword': null,
    'font-family-name-quotes': null,
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'declaration-empty-line-before': null,
    'rule-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'property-no-deprecated': null,
    'declaration-property-value-keyword-no-deprecated': null,
    'property-no-vendor-prefix': null,
    'selector-no-vendor-prefix': null,
    'value-no-vendor-prefix': null,
    'import-notation': null,
    'selector-not-notation': null,
    'media-feature-range-notation': null,
  },
  ignoreFiles: ['dist/**', 'node_modules/**'],
};
