// Shell / Bash tokenizer. Variables (`$VAR`, `${...}`) are matched before the
// `#` comment rule can fire, so `${#arr}` stays a variable.

import { scan, wordRegex } from './scanner.js';

const KEYWORDS = [
  'if',
  'then',
  'elif',
  'else',
  'fi',
  'for',
  'while',
  'until',
  'do',
  'done',
  'case',
  'esac',
  'function',
  'in',
  'select',
  'return',
  'break',
  'continue',
  'local',
  'export',
  'readonly',
  'declare',
  'typeset',
  'set',
  'unset',
  'shift',
  'exit',
  'source',
  'alias',
];

const BUILTINS = [
  'echo',
  'printf',
  'read',
  'cd',
  'pwd',
  'ls',
  'cat',
  'grep',
  'sed',
  'awk',
  'cut',
  'sort',
  'uniq',
  'head',
  'tail',
  'find',
  'xargs',
  'curl',
  'wget',
  'git',
  'npm',
  'pnpm',
  'yarn',
  'node',
  'python',
  'pip',
  'docker',
  'kubectl',
  'make',
  'chmod',
  'chown',
  'mkdir',
  'rmdir',
  'rm',
  'cp',
  'mv',
  'touch',
  'test',
  'sudo',
  'env',
  'which',
  'kill',
  'ps',
  'tar',
  'ssh',
];

const RULES = [
  { type: 'comment', re: /#[^\n]*/y },
  { type: 'string', re: /"(?:[^"\\]|\\.)*"?/y },
  { type: 'string', re: /'[^']*'?/y },
  { type: 'variable', re: /\$\{[^}\n]*\}?|\$[A-Za-z_]\w*|\$[@*#?$!0-9-]/y },
  { type: 'keyword', re: wordRegex(KEYWORDS) },
  { type: 'builtin', re: wordRegex(BUILTINS) },
  { type: 'attribute', re: /(?:^|\s)-{1,2}[A-Za-z][\w-]*/y },
  { type: 'number', re: /\b\d+\b/y },
  { type: 'operator', re: /\|\||&&|[|&;<>]+/y },
  { type: 'punctuation', re: /[(){}[\]]/y },
];

export function tokenizeShell(source) {
  return scan(source, RULES);
}
